# Generated by Django 6.0.1 on 2026-01-24 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_original', models.TextField(help_text='Texto bruto da anamnese digitado pelo médico')),
                ('texto_melhorado', models.TextField(help_text='Texto processado e refinado pela IA')),
                ('cid_sugerido', models.CharField(help_text='Código CID-10 sugerido', max_length=20)),
                ('principais_sintomas', models.JSONField(help_text='Lista de sintomas identificados (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Anamnese',
                'verbose_name_plural': 'Anamneses',
                'ordering': ['-created_at'],
            },
        ),
    ]
