# Generated by Django 6.0.1 on 2026-01-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='cid_sugerido',
            field=models.CharField(help_text='Código CID-10 sugerido', max_length=100),
        ),
    ]
