# Generated by Django 6.0.1 on 2026-01-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0002_alter_anamnese_cid_sugerido'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnese',
            name='tempo_processamento',
            field=models.FloatField(default=0.0, help_text='Tempo em segundos que a IA levou para processar'),
        ),
    ]
